name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # 🐳 Build Docker Image
    - name: Build Docker Image
      run: |
        cd app
        docker build -t devsecops-app .

    # 🔐 Scan for Secrets (Gitleaks)
    - name: Run Gitleaks Scan
      uses: zricethezav/gitleaks-action@v2

    # 🛡 Scan Docker Image (Trivy)
    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: devsecops-app
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH